### PR TITLE
V1.2

### LINKED ISSUE #6: add version of script used to html
Add version to footer, maybe use https://github.com/moka-guys/automate_demultiplex/blob/master/git_tag.py

### LINKED ISSUE #7: send emails to users when trend analysis updated
Can we ID if it's a WES/custom panel/cancer run?
Use the email code from automate demultiplexing scripts

### LINKED ISSUE #8: extra plot
For WES 
Histogram/bar chart of Peddy correct sex (counts of true/false)
(Peddy not relevant to custom panels)

### LINKED ISSUE #9: extra plot - fastqc
total sequences (millions)
The thresholds will be defined once the plots are visible.
WES and possibly other panels

### LINKED ISSUE #10: Amendments to plots
1. Add horizontal line at 150 as minimum cut off on picard insert sizes plot
2. Q30 per-sequencer plots - add horizontal line at 74 or 76 - need further information about whether this is either or or for different sequencers.
3. Total sequences plot needs to be altered to display the percentage of samples that fall within 20% of the average of the run. This would be calculated on a per panel basis and aggregated into a single plot.

### LINKED ISSUE #11: peddy sex check plot
What does 'unknown' plot as - True or False?

### PR DESCRIPTION
**Pull request by RachelDuffin**
1. Add functionality for running in development mode (user-visible part must not be affected by development work)
2. Add a new SWIFT trend report
3. Add new per-sequencer trend reports (2 NextSeqs, 2 MiSeqs and one NovaSeq)
4. Add new box plot types and improve existing plots. Closes #8 Closes #9 Closes #10 Closes #11
5. Add email alert functionality. Closes #7
6. Make archived trend reports user-accessible
7. Fix caching issues to ensure most up-to-date plots are user visible
8. Add script version number to trend reports and email alerts. Closes #6 

Script has been tested:
- Runs checked to ensure that the expected runs for inclusion were included in the correct reports and the correct plots within the reports. All as expected.
- Each plot then tested to ensure values have been correctly calculated by the script (ensuring they cover differing ways the code is applied according to the specification in the config file). Again, all as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14)

### CODE REVIEW

**Review by ErinPeat — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14)* status: all files reviewed, 5 unresolved discussions (waiting on @Graeme-Smith, @natashapinto, and @RachelDuffin)

___
*[README.md, line 57 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX3T626bM1JQNCT1so:-MZX3T633deC85ml8Pp6:b3z100m) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/README.md#L57)):*
> ```Markdown
> * The index.html file is updated whenever a new multiqc report is uploaded
> * The date modified timestamp is assessed to see if it's within the last x hours (where x is the frequency the script is run - config.run_frequency)
> * Script is run if timestamp is more recent than the frequency the script is run 
> ```

Does this make sense? Not sure what you're trying to say! 
___
*[read_qc_files.py, line 55 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX4E_QDfb343IfB9IZ:-MZX4E_R9nPYi9u2GH40:bpwo2g3) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L55)):*
> ```Python
>     if args.dev:
>         inputs.update(config.general_config['development'])
>         copyfile(src=config.general_config["production"]["index_file"], dst=inputs["index_file"])
> ```

What is dst? Comment or better variable  name? 
___
*[read_qc_files.py, line 92 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX4aWpDuWv160s37zj:-MZX4aWpDuWv160s37zk:bz771ah) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L92)):*
> ```Python
>     dir.
>     """
>     t = tempfile.mkdtemp()
> ```

Whats t? Better variable name needed 
___
*[read_qc_files.py, line 363 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX5kofBSMW0RQKtb0Q:-MZX5kog0qqUytApdAxd:bqkap0k) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L363)):*
> ```Python
>         sorted_run_list = sorted_runs(os.listdir(self.input_folder), self.runtype)
>         run_name_dictionary = {}
>         for i in range(1, len(sorted_run_list) + 1):
> ```

Avoid using single letters for variables : )
___
*[read_qc_files.py, line 749 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX7FZ0A2uH_uWw8H0f:-MZX7FZ0A2uH_uWw8H0g:b-13mpsn) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L749)):*
> ```Python
>             methods = inspect.getmembers(t, predicate=inspect.ismethod)
>             t.call_tools(methods)
>             e = Emails(input_folder=inputs["input_folder"], runtype=runtype, wes_email=inputs["wes_email"],
> ```

no tiny single e please

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14)* status: 16 of 18 files reviewed, 5 unresolved discussions (waiting on @ErinPeat, @Graeme-Smith, and @natashapinto)

___
*[README.md, line 57 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX3T626bM1JQNCT1so:-MZXGxlS0fT2tV_GrZ-h:b-n578m8) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/README.md#L57)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Does this make sense? Not sure what you're trying to say! 
</blockquote></details>

Have updated this - hopefully it now makes more sense. 
___
*[read_qc_files.py, line 55 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX4E_QDfb343IfB9IZ:-MZXJDzy0Vb91ScW5tKq:b-p5m40s) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L55)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

What is dst? Comment or better variable  name? 
</blockquote></details>

Discussed & agreed ok to keep as src and dst
___
*[read_qc_files.py, line 92 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX4aWpDuWv160s37zj:-MZXKRXt9ip0Yio_ly5I:bohghlg) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L92)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Whats t? Better variable name needed 
</blockquote></details>

It is a temporary directory path. changed variable name to tempdirpath
___
*[read_qc_files.py, line 363 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX5kofBSMW0RQKtb0Q:-MZXIhtaBbmvH5p532ql:b-k8jqqf) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L363)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Avoid using single letters for variables : )
</blockquote></details>

Changed to 'value'
___
*[read_qc_files.py, line 749 at r2](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-MZX7FZ0A2uH_uWw8H0f:-MZXInf-94mvAwZj5YPQ:bzbrsfz) ([raw file](https://github.com/moka-guys/trend_analysis/blob/d0c4bfa66db948160dc71379d04cb4f0fa2f61af/read_qc_files.py#L749)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

no tiny single e please 
</blockquote></details>

Ah yes, changed t to trend_report and e to email

**Review by RachelDuffin — COMMENTED** [review]
Added changes as requested

> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14#-:-MZXLBVA4WE5kRevALrY:b-2n9z26)* status: 16 of 18 files reviewed, 5 unresolved discussions (waiting on @ErinPeat, @Graeme-Smith, and @natashapinto)

**Review by ErinPeat — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith and @natashapinto)

**Review by ErinPeat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith and @natashapinto)

**Pull request merged**
