### PR TITLE
fix issue with check_for_update function

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/17)

### CODE REVIEW

**Review by natashapinto — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/17)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/trend_analysis/17#-M_5uafQ6f2ugzOFdiMG:-M_5uafQ6f2ugzOFdiMH:bi77yoc) ([raw file](https://github.com/moka-guys/trend_analysis/blob/7f7ebbdf4bd64d115b407f41684b3dd9aff9df0c/README.md#L1)):*
> ```Markdown
> # trend_analysis_v1.2The main script in this repository is `read_qc_files.py`
> ```

1.2.1?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/17)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/trend_analysis/17#-M_5uafQ6f2ugzOFdiMG:-M_6eG9C98cJasF9oW4C:b-896fix) ([raw file](https://github.com/moka-guys/trend_analysis/blob/7f7ebbdf4bd64d115b407f41684b3dd9aff9df0c/README.md#L1)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

1.2.1?
</blockquote></details>

Done.

**Review by natashapinto — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/trend_analysis/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
